kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker:latest
  settings:
    repo: j33r/deluge
    tags: latest
    dockerfile: Dockerfile
    username: j33r
    password:
      from_secret: DOCKER_HUB_TOKKEN
  when:
    branch:
      - master
    event:
      exclude:
        - pull_request

- name: test
  image: plugins/docker:latest
  settings:
    repo: j33r/deluge
    tags: latest
    dockerfile: Dockerfile
    username: j33r
    password:
      from_secret: DOCKER_HUB_TOKKEN
    dry_run: true
  when:
    event:
      - pull_request
